on: [push, pull_request]
name: Test
jobs:
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure Composer allow-plugins for GrumPHP
        run: composer config --no-interaction allow-plugins.phpro/grumphp true
      - name: Install Dependencies for BC Check
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php: ['7.4', '8.0', '8.1']
        composer-options: ['', '--prefer-lowest']
        composer-versions: ['composer:v2']
      fail-fast: true
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.composer-versions }}
          extensions: xdebug, mbstring, posix
      - name: Configure Composer allow-plugins for GrumPHP
        run: composer config --no-interaction allow-plugins.phpro/grumphp true
      - name: Install Project Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Check Versions
        run: |
          php -v
          php -m
          composer --version
      - name: Get composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        if: matrix.php != '8.1'
        run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}
      - name: Install dependencies (Ignore platform)
        if: matrix.php == '8.1'
        run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }} --ignore-platform-req=php
      - name: Set git variables
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Run GrumPHP Tests
        run: php vendor/bin/grumphp run --no-interaction --tasks=sequential
        continue-on-error: ${{ matrix.php == '8.1' && matrix.composer-options == '--prefer-lowest' }}
